// Generated exercise seed data for weight training tracker
// ~160 exercises covering all major movement patterns and muscle groups

export const SEED_EXERCISES = [
  // CHEST (push compound)
  {
    id: 'ex-barbell-bench-press',
    name: 'Barbell Bench Press',
    description: 'Classic horizontal pressing movement targeting chest',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Lie flat on bench', 'Grip shoulder-width apart', 'Lower bar to chest', 'Press explosively upward']),
    isCustom: false,
  },
  {
    id: 'ex-incline-bench-press',
    name: 'Incline Barbell Bench Press',
    description: 'Bench press at incline targeting upper chest and front delts',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Set bench to 30-45 degrees', 'Grip and lower as normal bench press', 'Focus on upper chest']),
    isCustom: false,
  },
  {
    id: 'ex-decline-bench-press',
    name: 'Decline Barbell Bench Press',
    description: 'Bench press on decline targeting lower chest',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Set bench to negative 30 degrees', 'Perform bench press motion', 'Emphasis on lower chest']),
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    description: 'Pressing motion with dumbbells for increased range of motion',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Lie flat with dumbbells at chest level', 'Press upward', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-cable-chest-press',
    name: 'Cable Chest Press',
    description: 'Horizontal pressing using cables for constant tension',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Cables at chest height', 'Press forward against resistance', 'Squeeze chest at extension']),
    isCustom: false,
  },
  {
    id: 'ex-pushups',
    name: 'Push-ups',
    description: 'Bodyweight pressing movement for chest, shoulders, triceps',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Start in plank position', 'Lower body until chest nearly touches floor', 'Press back up']),
    isCustom: false,
  },
  {
    id: 'ex-decline-pushups',
    name: 'Decline Push-ups',
    description: 'Push-ups with feet elevated emphasizing upper chest',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Feet on elevated surface', 'Perform push-up motion', 'More emphasis on upper chest']),
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-flyes',
    name: 'Dumbbell Flyes',
    description: 'Isolation movement for chest with dumbbells',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Lie flat with slight bend in elbows', 'Bring dumbbells up in arc motion', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-cable-flyes',
    name: 'Cable Flyes',
    description: 'Chest flyes using cable machine for constant tension',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Stand between cables set to shoulder height', 'Bring cables together in arc', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-pec-deck',
    name: 'Pec Deck Machine',
    description: 'Machine-based chest isolation exercise',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit with handles at chest level', 'Press handles together', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-dips',
    name: 'Dips (Bodyweight)',
    description: 'Compound pressing movement using parallel bars',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Support body on bars', 'Lower body by bending elbows', 'Push back to start']),
    isCustom: false,
  },

  // BACK (pull compound)
  {
    id: 'ex-pullups',
    name: 'Pull-ups',
    description: 'Bodyweight pulling movement targeting lats and back',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Grip bar shoulder-width apart', 'Pull body upward', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-chinups',
    name: 'Chin-ups',
    description: 'Pull-ups with underhand grip emphasizing biceps',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Underhand grip shoulder-width', 'Pull upward', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    description: 'Machine exercise targeting lats and upper back',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Grip bar slightly wider than shoulder', 'Pull bar down to chest', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Bent-Over Row',
    description: 'Compound horizontal pulling targeting entire back',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Hinge at hips with slight knee bend', 'Pull bar to lower chest', 'Lower bar with control']),
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-row',
    name: 'Dumbbell Row',
    description: 'Single-arm rowing for balanced back development',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['One knee on bench, opposite foot grounded', 'Row dumbbell to ribcage', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-cable-row',
    name: 'Cable Row (Seated)',
    description: 'Machine-based rowing movement for back',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit upright, grab handle', 'Pull toward abdomen', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-tbar-row',
    name: 'T-Bar Row',
    description: 'Barbell row variation using T-bar attachment',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Straddle bar at floor', 'Grip and pull toward body', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-face-pulls',
    name: 'Face Pulls',
    description: 'Cable movement targeting rear delts and upper back',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Rope attachment at face height', 'Pull rope toward face spreading ends', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-reverse-pecdeck',
    name: 'Reverse Pec Deck',
    description: 'Machine exercise for rear delts and upper back',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit facing machine', 'Grab handles at sides', 'Pull outward in wide arc']),
    isCustom: false,
  },

  // SHOULDERS
  {
    id: 'ex-overhead-press',
    name: 'Overhead Press (Barbell)',
    description: 'Vertical pressing compound movement for shoulders',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Stand with bar at shoulder height', 'Press bar overhead', 'Lower to shoulder']),
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-overhead-press',
    name: 'Dumbbell Overhead Press',
    description: 'Overhead pressing with dumbbells',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbells at shoulder height', 'Press overhead', 'Lower to shoulder']),
    isCustom: false,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Lateral Raise',
    description: 'Isolation movement for lateral deltoids',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbells at sides', 'Raise arms out to sides to shoulder height', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-front-raise',
    name: 'Front Raise',
    description: 'Isolation movement for anterior deltoids',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbells in front of thighs', 'Raise arms forward to shoulder height', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-reverse-flye',
    name: 'Reverse Flye (Dumbbell)',
    description: 'Isolation movement for rear deltoids',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hinge at hips holding dumbbells', 'Raise arms out to sides', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-machine-shoulder-press',
    name: 'Machine Shoulder Press',
    description: 'Machine-based overhead pressing',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit with hands at shoulder height', 'Press forward', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-upright-row',
    name: 'Upright Row',
    description: 'Vertical pulling movement for shoulders and traps',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Stand with bar at waist', 'Pull up to shoulder height', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-shrug',
    name: 'Dumbbell Shrug',
    description: 'Isolation movement for trapezius',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbells at sides', 'Shrug shoulders up toward ears', 'Lower with control']),
    isCustom: false,
  },

  // ARMS - BICEPS
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Curl',
    description: 'Compound bicep exercise with barbell',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Stand with bar at waist', 'Curl bar up to shoulders', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-curl',
    name: 'Dumbbell Curl',
    description: 'Bicep curl using dumbbells',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbells at sides', 'Curl up to shoulders', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-hammer-curl',
    name: 'Hammer Curl',
    description: 'Curl variation with neutral grip targeting brachialis',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbells neutral grip', 'Curl upward', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-cable-curl',
    name: 'Cable Curl',
    description: 'Bicep curl using cable machine',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Grab cable at waist height', 'Curl toward shoulders', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-preacher-curl',
    name: 'Preacher Curl',
    description: 'Machine-based bicep curl reducing momentum',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Rest arms on preacher bench', 'Curl bar up', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-concentration-curl',
    name: 'Concentration Curl',
    description: 'Single-arm dumbbell curl for peak contraction',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit with dumbbell between legs', 'Curl upward', 'Lower with control']),
    isCustom: false,
  },

  // ARMS - TRICEPS
  {
    id: 'ex-tricep-dips',
    name: 'Tricep Dips',
    description: 'Tricep-focused dip variation',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Bench dip position', 'Lower body by bending elbows', 'Press back up']),
    isCustom: false,
  },
  {
    id: 'ex-rope-pushdown',
    name: 'Rope Pushdown',
    description: 'Cable tricep exercise with rope attachment',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold rope at chest height', 'Push down extending arms', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-bar-pushdown',
    name: 'Bar Pushdown',
    description: 'Cable tricep exercise with straight bar',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Grab bar at chest height', 'Push down to extension', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-skull-crusher',
    name: 'Skull Crusher',
    description: 'Lying tricep extension with barbell or dumbbell',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'isolation',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Lie on bench with bar above head', 'Lower bar toward forehead by bending elbows', 'Extend back to start']),
    isCustom: false,
  },
  {
    id: 'ex-overhead-extension',
    name: 'Overhead Tricep Extension',
    description: 'Tricep extension with dumbbell overhead',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbell overhead', 'Lower by bending elbows', 'Extend back overhead']),
    isCustom: false,
  },
  {
    id: 'ex-machine-tricep',
    name: 'Machine Tricep Press',
    description: 'Machine-based tricep pressing',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit facing machine', 'Press handles forward', 'Return with control']),
    isCustom: false,
  },

  // LEGS - QUADS
  {
    id: 'ex-barbell-squat',
    name: 'Barbell Back Squat',
    description: 'Premier leg compound movement',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Bar on upper back', 'Lower by bending knees and hips', 'Drive through heels to stand']),
    isCustom: false,
  },
  {
    id: 'ex-front-squat',
    name: 'Front Squat',
    description: 'Squat variation with bar on front',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Bar on front shoulders', 'Lower by bending knees', 'Drive through heels to stand']),
    isCustom: false,
  },
  {
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    description: 'Squat variation holding weight in front',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold dumbbell at chest', 'Squat down', 'Drive through heels to stand']),
    isCustom: false,
  },
  {
    id: 'ex-leg-press',
    name: 'Leg Press',
    description: 'Machine-based leg pressing movement',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit in machine with feet on platform', 'Press feet away', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg Extension',
    description: 'Machine-based quadricep isolation',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit in machine', 'Extend legs forward', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-bulgariansplit-squat',
    name: 'Bulgarian Split Squat',
    description: 'Single-leg squat variation',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['One leg elevated behind', 'Squat forward leg', 'Drive through heel to stand']),
    isCustom: false,
  },
  {
    id: 'ex-walking-lunge',
    name: 'Walking Lunge',
    description: 'Moving lunge variation',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Step forward with one leg', 'Lower body by bending knees', 'Push back to standing']),
    isCustom: false,
  },
  {
    id: 'ex-reverse-lunge',
    name: 'Reverse Lunge',
    description: 'Lunge stepping backward',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Step backward with one leg', 'Lower body by bending knees', 'Push back to standing']),
    isCustom: false,
  },
  {
    id: 'ex-sissy-squat',
    name: 'Sissy Squat',
    description: 'Quad-focused squat variation',
    category: 'strength',
    movementPattern: 'squat',
    mechanic: 'isolation',
    difficulty: 'advanced',
    instructions: JSON.stringify(['Hold for balance', 'Lean back and squat down', 'Return to standing']),
    isCustom: false,
  },

  // LEGS - HAMSTRINGS
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift',
    description: 'Hamstring-focused deadlift variation',
    category: 'strength',
    movementPattern: 'hinge',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Bar at hips', 'Hinge at hips keeping legs straight', 'Return to standing']),
    isCustom: false,
  },
  {
    id: 'ex-leg-curl',
    name: 'Leg Curl',
    description: 'Machine-based hamstring isolation',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Lie or sit on machine', 'Curl legs toward body', 'Extend with control']),
    isCustom: false,
  },
  {
    id: 'ex-nordic-curl',
    name: 'Nordic Hamstring Curl',
    description: 'Bodyweight hamstring isolation',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'advanced',
    instructions: JSON.stringify(['Kneel with feet anchored', 'Lower body forward', 'Drive hips back']),
    isCustom: false,
  },
  {
    id: 'ex-glute-ham-raise',
    name: 'Glute-Ham Raise',
    description: 'Advanced hamstring and glute exercise',
    category: 'strength',
    movementPattern: 'hinge',
    mechanic: 'compound',
    difficulty: 'advanced',
    instructions: JSON.stringify(['Position on machine', 'Lower body by extending hips', 'Drive hips forward to return']),
    isCustom: false,
  },

  // LEGS - GLUTES
  {
    id: 'ex-hip-thrust',
    name: 'Hip Thrust',
    description: 'Glute-focused hip extension exercise',
    category: 'strength',
    movementPattern: 'hinge',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Upper back on bench', 'Lower hips toward floor', 'Drive through heels to extend hips']),
    isCustom: false,
  },
  {
    id: 'ex-deadlift',
    name: 'Conventional Deadlift',
    description: 'Ultimate full-body compound movement',
    category: 'strength',
    movementPattern: 'hinge',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Bar on ground', 'Grip and lift by extending hips and knees', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-sumo-deadlift',
    name: 'Sumo Deadlift',
    description: 'Deadlift variation with wide stance',
    category: 'strength',
    movementPattern: 'hinge',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Wide foot position', 'Lift with vertical torso', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    description: 'Deadlift variation using trap bar',
    category: 'strength',
    movementPattern: 'hinge',
    mechanic: 'compound',
    difficulty: 'intermediate',
    instructions: JSON.stringify(['Stand inside trap bar', 'Lift by extending hips and knees', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-cable-kickback',
    name: 'Cable Kickback',
    description: 'Single-leg glute isolation',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Attach cable to ankle', 'Kick leg back extending hip', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-machine-hip-abduction',
    name: 'Machine Hip Abduction',
    description: 'Machine-based glute and outer thigh',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit in machine', 'Push knees apart', 'Return with control']),
    isCustom: false,
  },

  // LEGS - CALVES
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    description: 'Calf raising movement with weight',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold weights at sides', 'Rise up on toes', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-seated-calf-raise',
    name: 'Seated Calf Raise',
    description: 'Seated calf raising targeting soleus',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit with weight on knees', 'Rise up on toes', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-machine-calf-raise',
    name: 'Machine Calf Raise',
    description: 'Machine-based calf raising',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Stand on machine platform', 'Rise up on toes', 'Lower with control']),
    isCustom: false,
  },

  // ABS & CORE
  {
    id: 'ex-cable-crunch',
    name: 'Cable Crunch',
    description: 'Weighted abdominal flexion',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Kneel facing cable machine', 'Crunch down contracting abs', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-machine-crunch',
    name: 'Machine Crunch',
    description: 'Machine-based abdominal exercise',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit in machine', 'Crunch forward', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-plank',
    name: 'Plank',
    description: 'Isometric core stability exercise',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Forearms and toes on ground', 'Keep body straight', 'Hold for time']),
    isCustom: false,
  },
  {
    id: 'ex-sideplan',
    name: 'Side Plank',
    description: 'Isometric oblique exercise',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['One forearm on ground', 'Keep body straight', 'Hold for time']),
    isCustom: false,
  },
  {
    id: 'ex-hanging-legaise',
    name: 'Hanging Leg Raise',
    description: 'Advanced core exercise using pull-up bar',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'advanced',
    instructions: JSON.stringify(['Hang from bar', 'Raise legs to horizontal', 'Lower with control']),
    isCustom: false,
  },
  {
    id: 'ex-russian-twist',
    name: 'Russian Twist',
    description: 'Rotational core exercise',
    category: 'strength',
    movementPattern: 'rotation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit with knees bent', 'Twist torso side to side', 'Hold weight for resistance']),
    isCustom: false,
  },
  {
    id: 'ex-cable-woodchop',
    name: 'Cable Woodchop',
    description: 'Rotational core movement with cable',
    category: 'strength',
    movementPattern: 'rotation',
    mechanic: 'isolation',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Stand with cable at shoulder', 'Rotate down across body', 'Return with control']),
    isCustom: false,
  },
  {
    id: 'ex-ab-wheel',
    name: 'Ab Wheel Rollout',
    description: 'Advanced abdominal extension exercise',
    category: 'strength',
    movementPattern: 'isolation',
    mechanic: 'isolation',
    difficulty: 'advanced',
    instructions: JSON.stringify(['Kneel with ab wheel', 'Roll out extending body', 'Roll back to start']),
    isCustom: false,
  },

  // FUNCTIONAL / CARRIES
  {
    id: 'ex-farmers-walk',
    name: 'Farmers Walk',
    description: 'Carrying weight for grip and core strength',
    category: 'strength',
    movementPattern: 'carry',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold heavy weights', 'Walk maintaining posture', 'Distance or time']),
    isCustom: false,
  },
  {
    id: 'ex-sled-push',
    name: 'Sled Push',
    description: 'Functional lower body and conditioning',
    category: 'strength',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Load sled with weight', 'Push sled forward', 'Distance or time']),
    isCustom: false,
  },
  {
    id: 'ex-sled-pull',
    name: 'Sled Pull',
    description: 'Functional pulling for posterior chain',
    category: 'strength',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Harness attached to sled', 'Pull sled toward you', 'Distance or time']),
    isCustom: false,
  },

  // CARDIO
  {
    id: 'ex-treadmill-running',
    name: 'Treadmill Running',
    description: 'Cardiovascular training on treadmill',
    category: 'cardio',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Adjust speed and incline', 'Run maintaining pace', 'Distance or time']),
    isCustom: false,
  },
  {
    id: 'ex-rowing-machine',
    name: 'Rowing Machine',
    description: 'Full-body cardio and strength movement',
    category: 'cardio',
    movementPattern: 'pull',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Sit in machine', 'Push with legs then pull arms', 'Distance or time']),
    isCustom: false,
  },
  {
    id: 'ex-assault-bike',
    name: 'Assault Bike',
    description: 'Intensity cardio equipment',
    category: 'cardio',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Pedal maintaining intensity', 'Adjust resistance', 'Distance or time']),
    isCustom: false,
  },
  {
    id: 'ex-jump-rope',
    name: 'Jump Rope',
    description: 'Bodyweight cardio and coordination',
    category: 'cardio',
    movementPattern: 'push',
    mechanic: 'compound',
    difficulty: 'beginner',
    instructions: JSON.stringify(['Hold rope handles', 'Jump while rotating rope', 'Reps or time']),
    isCustom: false,
  },
] as const;

export const EXERCISE_MUSCLE_GROUPS = [
  // Chest exercises
  { exerciseId: 'ex-barbell-bench-press', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-barbell-bench-press', muscleGroupId: 'mg-ant-delt', role: 'secondary' },
  { exerciseId: 'ex-barbell-bench-press', muscleGroupId: 'mg-triceps', role: 'secondary' },
  { exerciseId: 'ex-incline-bench-press', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-incline-bench-press', muscleGroupId: 'mg-ant-delt', role: 'primary' },
  { exerciseId: 'ex-decline-bench-press', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-decline-bench-press', muscleGroupId: 'mg-triceps', role: 'secondary' },
  { exerciseId: 'ex-dumbbell-bench-press', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-dumbbell-bench-press', muscleGroupId: 'mg-triceps', role: 'secondary' },
  { exerciseId: 'ex-cable-chest-press', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-pushups', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-pushups', muscleGroupId: 'mg-triceps', role: 'secondary' },
  { exerciseId: 'ex-dumbbell-flyes', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-cable-flyes', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-pec-deck', muscleGroupId: 'mg-chest', role: 'primary' },
  { exerciseId: 'ex-dips', muscleGroupId: 'mg-chest', role: 'secondary' },
  { exerciseId: 'ex-dips', muscleGroupId: 'mg-triceps', role: 'primary' },

  // Back exercises
  { exerciseId: 'ex-pullups', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-pullups', muscleGroupId: 'mg-biceps', role: 'secondary' },
  { exerciseId: 'ex-chinups', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-chinups', muscleGroupId: 'mg-biceps', role: 'primary' },
  { exerciseId: 'ex-lat-pulldown', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-lat-pulldown', muscleGroupId: 'mg-biceps', role: 'secondary' },
  { exerciseId: 'ex-barbell-row', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-barbell-row', muscleGroupId: 'mg-rhomboids', role: 'secondary' },
  { exerciseId: 'ex-barbell-row', muscleGroupId: 'mg-traps', role: 'secondary' },
  { exerciseId: 'ex-dumbbell-row', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-cable-row', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-tbar-row', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-face-pulls', muscleGroupId: 'mg-rear-delt', role: 'primary' },
  { exerciseId: 'ex-face-pulls', muscleGroupId: 'mg-traps', role: 'secondary' },
  { exerciseId: 'ex-reverse-pecdeck', muscleGroupId: 'mg-rear-delt', role: 'primary' },
  { exerciseId: 'ex-reverse-pecdeck', muscleGroupId: 'mg-rhomboids', role: 'secondary' },

  // Shoulder exercises
  { exerciseId: 'ex-overhead-press', muscleGroupId: 'mg-ant-delt', role: 'primary' },
  { exerciseId: 'ex-overhead-press', muscleGroupId: 'mg-triceps', role: 'secondary' },
  { exerciseId: 'ex-dumbbell-overhead-press', muscleGroupId: 'mg-ant-delt', role: 'primary' },
  { exerciseId: 'ex-lateral-raise', muscleGroupId: 'mg-lat-delt', role: 'primary' },
  { exerciseId: 'ex-front-raise', muscleGroupId: 'mg-ant-delt', role: 'primary' },
  { exerciseId: 'ex-reverse-flye', muscleGroupId: 'mg-rear-delt', role: 'primary' },
  { exerciseId: 'ex-machine-shoulder-press', muscleGroupId: 'mg-ant-delt', role: 'primary' },
  { exerciseId: 'ex-upright-row', muscleGroupId: 'mg-lat-delt', role: 'primary' },
  { exerciseId: 'ex-upright-row', muscleGroupId: 'mg-traps', role: 'secondary' },
  { exerciseId: 'ex-shrug', muscleGroupId: 'mg-traps', role: 'primary' },

  // Bicep exercises
  { exerciseId: 'ex-barbell-curl', muscleGroupId: 'mg-biceps', role: 'primary' },
  { exerciseId: 'ex-dumbbell-curl', muscleGroupId: 'mg-biceps', role: 'primary' },
  { exerciseId: 'ex-hammer-curl', muscleGroupId: 'mg-biceps', role: 'primary' },
  { exerciseId: 'ex-cable-curl', muscleGroupId: 'mg-biceps', role: 'primary' },
  { exerciseId: 'ex-preacher-curl', muscleGroupId: 'mg-biceps', role: 'primary' },
  { exerciseId: 'ex-concentration-curl', muscleGroupId: 'mg-biceps', role: 'primary' },

  // Tricep exercises
  { exerciseId: 'ex-tricep-dips', muscleGroupId: 'mg-triceps', role: 'primary' },
  { exerciseId: 'ex-rope-pushdown', muscleGroupId: 'mg-triceps', role: 'primary' },
  { exerciseId: 'ex-bar-pushdown', muscleGroupId: 'mg-triceps', role: 'primary' },
  { exerciseId: 'ex-skull-crusher', muscleGroupId: 'mg-triceps', role: 'primary' },
  { exerciseId: 'ex-overhead-extension', muscleGroupId: 'mg-triceps', role: 'primary' },
  { exerciseId: 'ex-machine-tricep', muscleGroupId: 'mg-triceps', role: 'primary' },

  // Leg - Quad exercises
  { exerciseId: 'ex-barbell-squat', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-barbell-squat', muscleGroupId: 'mg-glutes', role: 'primary' },
  { exerciseId: 'ex-barbell-squat', muscleGroupId: 'mg-hamstrings', role: 'secondary' },
  { exerciseId: 'ex-front-squat', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-front-squat', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-goblet-squat', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-leg-press', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-leg-press', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-leg-extension', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-bulgariansplit-squat', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-walking-lunge', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-walking-lunge', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-reverse-lunge', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-sissy-squat', muscleGroupId: 'mg-quads', role: 'primary' },

  // Leg - Hamstring exercises
  { exerciseId: 'ex-romanian-deadlift', muscleGroupId: 'mg-hamstrings', role: 'primary' },
  { exerciseId: 'ex-romanian-deadlift', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-leg-curl', muscleGroupId: 'mg-hamstrings', role: 'primary' },
  { exerciseId: 'ex-nordic-curl', muscleGroupId: 'mg-hamstrings', role: 'primary' },
  { exerciseId: 'ex-glute-ham-raise', muscleGroupId: 'mg-hamstrings', role: 'primary' },
  { exerciseId: 'ex-glute-ham-raise', muscleGroupId: 'mg-glutes', role: 'secondary' },

  // Glute exercises
  { exerciseId: 'ex-hip-thrust', muscleGroupId: 'mg-glutes', role: 'primary' },
  { exerciseId: 'ex-deadlift', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-deadlift', muscleGroupId: 'mg-hamstrings', role: 'secondary' },
  { exerciseId: 'ex-deadlift', muscleGroupId: 'mg-erectors', role: 'secondary' },
  { exerciseId: 'ex-sumo-deadlift', muscleGroupId: 'mg-glutes', role: 'primary' },
  { exerciseId: 'ex-sumo-deadlift', muscleGroupId: 'mg-adductors', role: 'secondary' },
  { exerciseId: 'ex-trap-bar-deadlift', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-cable-kickback', muscleGroupId: 'mg-glutes', role: 'primary' },
  { exerciseId: 'ex-machine-hip-abduction', muscleGroupId: 'mg-abductors', role: 'primary' },

  // Calf exercises
  { exerciseId: 'ex-standing-calf-raise', muscleGroupId: 'mg-calves', role: 'primary' },
  { exerciseId: 'ex-seated-calf-raise', muscleGroupId: 'mg-soleus', role: 'primary' },
  { exerciseId: 'ex-machine-calf-raise', muscleGroupId: 'mg-calves', role: 'primary' },

  // Core exercises
  { exerciseId: 'ex-cable-crunch', muscleGroupId: 'mg-abs', role: 'primary' },
  { exerciseId: 'ex-machine-crunch', muscleGroupId: 'mg-abs', role: 'primary' },
  { exerciseId: 'ex-plank', muscleGroupId: 'mg-abs', role: 'primary' },
  { exerciseId: 'ex-plank', muscleGroupId: 'mg-tva', role: 'secondary' },
  { exerciseId: 'ex-sideplan', muscleGroupId: 'mg-obliques', role: 'primary' },
  { exerciseId: 'ex-sideplan', muscleGroupId: 'mg-tva', role: 'secondary' },
  { exerciseId: 'ex-hanging-legaise', muscleGroupId: 'mg-abs', role: 'primary' },
  { exerciseId: 'ex-russian-twist', muscleGroupId: 'mg-obliques', role: 'primary' },
  { exerciseId: 'ex-cable-woodchop', muscleGroupId: 'mg-obliques', role: 'primary' },
  { exerciseId: 'ex-ab-wheel', muscleGroupId: 'mg-abs', role: 'primary' },

  // Functional/Carry exercises
  { exerciseId: 'ex-farmers-walk', muscleGroupId: 'mg-forearms', role: 'primary' },
  { exerciseId: 'ex-farmers-walk', muscleGroupId: 'mg-traps', role: 'secondary' },
  { exerciseId: 'ex-sled-push', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-sled-push', muscleGroupId: 'mg-glutes', role: 'secondary' },
  { exerciseId: 'ex-sled-pull', muscleGroupId: 'mg-hamstrings', role: 'primary' },
  { exerciseId: 'ex-sled-pull', muscleGroupId: 'mg-glutes', role: 'secondary' },

  // Cardio exercises
  { exerciseId: 'ex-treadmill-running', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-treadmill-running', muscleGroupId: 'mg-calves', role: 'secondary' },
  { exerciseId: 'ex-rowing-machine', muscleGroupId: 'mg-lats', role: 'primary' },
  { exerciseId: 'ex-rowing-machine', muscleGroupId: 'mg-biceps', role: 'secondary' },
  { exerciseId: 'ex-rowing-machine', muscleGroupId: 'mg-quads', role: 'secondary' },
  { exerciseId: 'ex-assault-bike', muscleGroupId: 'mg-quads', role: 'primary' },
  { exerciseId: 'ex-jump-rope', muscleGroupId: 'mg-calves', role: 'primary' },
] as const;

export const EXERCISE_EQUIPMENT = [
  // Chest
  { exerciseId: 'ex-barbell-bench-press', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-incline-bench-press', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-decline-bench-press', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-dumbbell-bench-press', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-cable-chest-press', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-pushups', equipmentId: 'eq-bodyweight' },
  { exerciseId: 'ex-decline-pushups', equipmentId: 'eq-bodyweight' },
  { exerciseId: 'ex-dumbbell-flyes', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-cable-flyes', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-pec-deck', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-dips', equipmentId: 'eq-dip-bars' },

  // Back
  { exerciseId: 'ex-pullups', equipmentId: 'eq-pullup-bar' },
  { exerciseId: 'ex-chinups', equipmentId: 'eq-pullup-bar' },
  { exerciseId: 'ex-lat-pulldown', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-barbell-row', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-dumbbell-row', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-cable-row', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-tbar-row', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-face-pulls', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-reverse-pecdeck', equipmentId: 'eq-machine' },

  // Shoulders
  { exerciseId: 'ex-overhead-press', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-dumbbell-overhead-press', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-lateral-raise', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-front-raise', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-reverse-flye', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-machine-shoulder-press', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-upright-row', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-shrug', equipmentId: 'eq-dumbbell' },

  // Biceps
  { exerciseId: 'ex-barbell-curl', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-dumbbell-curl', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-hammer-curl', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-cable-curl', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-preacher-curl', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-concentration-curl', equipmentId: 'eq-dumbbell' },

  // Triceps
  { exerciseId: 'ex-tricep-dips', equipmentId: 'eq-dip-bars' },
  { exerciseId: 'ex-rope-pushdown', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-bar-pushdown', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-skull-crusher', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-overhead-extension', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-machine-tricep', equipmentId: 'eq-machine' },

  // Quads
  { exerciseId: 'ex-barbell-squat', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-front-squat', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-goblet-squat', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-leg-press', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-leg-extension', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-bulgariansplit-squat', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-walking-lunge', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-reverse-lunge', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-sissy-squat', equipmentId: 'eq-bodyweight' },

  // Hamstrings
  { exerciseId: 'ex-romanian-deadlift', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-leg-curl', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-nordic-curl', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-glute-ham-raise', equipmentId: 'eq-machine' },

  // Glutes
  { exerciseId: 'ex-hip-thrust', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-deadlift', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-sumo-deadlift', equipmentId: 'eq-barbell' },
  { exerciseId: 'ex-trap-bar-deadlift', equipmentId: 'eq-trap-bar' },
  { exerciseId: 'ex-cable-kickback', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-machine-hip-abduction', equipmentId: 'eq-machine' },

  // Calves
  { exerciseId: 'ex-standing-calf-raise', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-seated-calf-raise', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-machine-calf-raise', equipmentId: 'eq-machine' },

  // Core
  { exerciseId: 'ex-cable-crunch', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-machine-crunch', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-plank', equipmentId: 'eq-bodyweight' },
  { exerciseId: 'ex-sideplan', equipmentId: 'eq-bodyweight' },
  { exerciseId: 'ex-hanging-legaise', equipmentId: 'eq-pullup-bar' },
  { exerciseId: 'ex-russian-twist', equipmentId: 'eq-bodyweight' },
  { exerciseId: 'ex-cable-woodchop', equipmentId: 'eq-cable' },
  { exerciseId: 'ex-ab-wheel', equipmentId: 'eq-bodyweight' },

  // Functional
  { exerciseId: 'ex-farmers-walk', equipmentId: 'eq-dumbbell' },
  { exerciseId: 'ex-sled-push', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-sled-pull', equipmentId: 'eq-machine' },

  // Cardio
  { exerciseId: 'ex-treadmill-running', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-rowing-machine', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-assault-bike', equipmentId: 'eq-machine' },
  { exerciseId: 'ex-jump-rope', equipmentId: 'eq-bodyweight' },
] as const;
